// <auto-generated />
using System;
using BookFlix.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace BookFlix.API.Migrations
{
    [DbContext(typeof(BookFlixDbContext))]
    [Migration("20250530061946_added vector column for books db")]
    partial class addedvectorcolumnforbooksdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookFlix.API.Models.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(384)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RatingId");

                    b.HasIndex("Title", "Author", "Price")
                        .IsUnique();

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookFlix.API.Models.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc54bb0c-1d77-48c2-95ea-fd55f691db4c"),
                            Title = "Fiction"
                        },
                        new
                        {
                            Id = new Guid("17ea39ed-3066-44f6-a0c1-d97be6b15de9"),
                            Title = "Literature"
                        },
                        new
                        {
                            Id = new Guid("f0e0164e-a932-4a8b-ba41-291df0d439d5"),
                            Title = "Technology"
                        },
                        new
                        {
                            Id = new Guid("3edb015b-ec4e-45df-8390-b9c66281ab3f"),
                            Title = "History"
                        },
                        new
                        {
                            Id = new Guid("2fa56e3d-d9fb-4453-824a-9094580e5d52"),
                            Title = "Finance"
                        });
                });

            modelBuilder.Entity("BookFlix.API.Models.Domain.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RatingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3c7d69e-0c07-47db-a0fe-f7eb6160f568"),
                            RatingName = "Good"
                        },
                        new
                        {
                            Id = new Guid("4bb3890e-2acc-4ebe-9e5f-e0527b4b33cb"),
                            RatingName = "Average"
                        },
                        new
                        {
                            Id = new Guid("91f9aee4-d7d3-4ea1-b4ba-e6c11c37efe3"),
                            RatingName = "Bad"
                        });
                });

            modelBuilder.Entity("BookFlix.API.Models.Domain.Book", b =>
                {
                    b.HasOne("BookFlix.API.Models.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookFlix.API.Models.Domain.Rating", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Rating");
                });
#pragma warning restore 612, 618
        }
    }
}
